intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{msvc-std}: {hxx ixx txx mxx}{**} $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

if($cxx.class == 'gcc')
{
  cxx.poptions += -Wno-reserved-module-identifier
}

# Export options.
#
lib{msvc-std}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# Install into the msvc-std/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/msvc-std/
  install.subdirs = true
}
